apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-notebook
  namespace: lakehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-notebook
  template:
    metadata:
      labels:
        app: spark-notebook
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: spark-notebook
          #image: my-registry:30222/spark-notebook-custom:v1
          image: suyogbhalekar19/spark-notebook:v2
          ports:
          - containerPort: 8888
          - containerPort: 4040
          env:
          - name: TZ
            value: "Asia/Kolkata"
          - name: JUPYTER_ENABLE_LAB
            value: "yes"
          - name: GRANT_SUDO
            value: "yes"
          - name: JUPYTER_TOKEN
            valueFrom:
              configMapKeyRef:
                name: jupiter
                key: JUPYTER_TOKEN
          volumeMounts:
          - name: notebooks
            mountPath: /home/jovyan/work
            readOnly: false
          - name: spark-defaults
            mountPath: /usr/local/spark/conf/spark-defaults.conf
            subPath: spark-defaults.conf
          readinessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:100 /home"]
            #command: ["sh", "-c", "chmod -R 777 /home"]
          volumeMounts:
          - name: notebooks
            mountPath: /home/jovyan/work
      volumes:
        - name: notebooks
          persistentVolumeClaim:
            claimName: notebooks-pvc
        - name: spark-defaults
          configMap:
            name: spark-notebook-config
